### ISSUE TITLE
Fails if mapfile not found

### ISSUE THREAD

**Issue by robrecord** [David-Else/kitty-terminal-project-launcher#1]
When running, I get:

```
ep: line 47: mapfile: command not found
```

Would be good if a hint could be provided, if this command is not found, on how/where to install it.

**Comment by robrecord** [comment]
Actually, finding this is a bash builtin, it appears the latest version of bash on my system is not being invoked.

**Comment by David-Else** [comment]
What exact OS are you using?

**Comment by David-Else** [comment]
Thanks! Please let me know if you have any more problems.

**Comment by robrecord** [comment]
it’s macOS Ventura. I also have a homebrew-installed bash in /use/local/bin that I believe is a later version. 

Thanks David!
